language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
    - development
addons:
  ssh_known_hosts: git.wpengine.com
script:
  - pushd wp-content/themes/csismag; npm run build; popd
  - pushd wp-content/plugins/csismag-blocks; npm run build; popd
before_install:
  - openssl aes-256-cbc -K $encrypted_deec70939cbe_key -iv $encrypted_deec70939cbe_iv -in csismag_rsa.enc -out /tmp/csismag_rsa -d
install:
  - pushd wp-content/themes/csismag; npm install; popd
  - pushd wp-content/plugins/csismag-blocks; npm install; popd
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy-development.sh && sh deploy-development.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy-staging.sh && sh deploy-staging.sh
    on:
      branch: master
