name: WP Engine Git Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Theme: Install dependencies"
        working-directory: ./wp-content/themes/csismag
        run: npm ci

      - name: "Theme: Build"
        working-directory: ./wp-content/themes/csismag
        run: npm run build && rm -rf node_modules

      - name: "Plugin: Install dependencies"
        working-directory: ./wp-content/plugins/csismag-blocks
        run: npm ci

      - name: "Plugin: Build"
        working-directory: ./wp-content/plugins/csismag-blocks
        run: npm run build && rm -rf node_modules

      - name: Git fetch
        run: git fetch --prune --unshallow

      - name: Push to WP Engine
        uses: epogeedesign/github-action-wpengine-git-deploy@master
        env:
          WPE_ENVIRONMENT_NAME: ${{ secrets.WPE_DEV_ENV_NAME }}
          WPE_SSH_KEY_PRIVATE: ${{ secrets.WPE_SSH_KEY_PRIVATE }}
          WPE_SSH_KEY_PUBLIC: ${{ secrets.WPE_SSH_KEY_PUBLIC }}
          WPE_ENVIRONMENT: "production" # Do not change this
          WPE_LOCAL_BRANCH: "main" # Should match the name of the branch on line 4.
          WPE_GIT_INCLUDE: ".github/wpe-git-include.txt"
          WPE_GIT_EXCLUDE: ".github/wpe-git-exclude.txt"
